#pragma once

#include <array>
namespace tr::renderer {

enum GPUTimestampIndex {
  GPU_TIMESTAMP_INDEX_TOP,
  GPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM,
  GPU_TIMESTAMP_INDEX_SHADOW_BOTTOM,
  GPU_TIMESTAMP_INDEX_DEFERRED_BOTTOM,
  GPU_TIMESTAMP_INDEX_BOTTOM,
  GPU_TIMESTAMP_INDEX_IMGUI_TOP,
  GPU_TIMESTAMP_INDEX_IMGUI_BOTTOM,
  GPU_TIMESTAMP_INDEX_MAX,
  GPU_TIMESTAMP_INDEX_GBUFFER_TOP = GPU_TIMESTAMP_INDEX_TOP,
  GPU_TIMESTAMP_INDEX_SHADOW_TOP = GPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM,
  GPU_TIMESTAMP_INDEX_DEFERRED_TOP = GPU_TIMESTAMP_INDEX_SHADOW_BOTTOM,
  GPU_TIMESTAMP_INDEX_PRESENT_TOP = GPU_TIMESTAMP_INDEX_DEFERRED_BOTTOM,
  GPU_TIMESTAMP_INDEX_PRESENT_BOTTOM = GPU_TIMESTAMP_INDEX_BOTTOM,

};

enum CPUTimestampIndex {
  CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_TOP,
  CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_WAIT_FENCE,
  CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_BOTTOM,
  CPU_TIMESTAMP_INDEX_IMGUI_TOP,
  CPU_TIMESTAMP_INDEX_IMGUI_BOTTOM,
  CPU_TIMESTAMP_INDEX_DRAW_TOP,
  CPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM,
  CPU_TIMESTAMP_INDEX_SHADOW_BOTTOM,
  CPU_TIMESTAMP_INDEX_DRAW_BOTTOM,
  CPU_TIMESTAMP_INDEX_PRESENT_TOP,
  CPU_TIMESTAMP_INDEX_PRESENT_BOTTOM,
  CPU_TIMESTAMP_INDEX_MAX,
  CPU_TIMESTAMP_INDEX_GBUFFER_TOP = CPU_TIMESTAMP_INDEX_DRAW_TOP,
  CPU_TIMESTAMP_INDEX_SHADOW_TOP = CPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM,
  CPU_TIMESTAMP_INDEX_DEFERRED_TOP = CPU_TIMESTAMP_INDEX_SHADOW_BOTTOM,
  CPU_TIMESTAMP_INDEX_DEFERRED_BOTTOM = CPU_TIMESTAMP_INDEX_DRAW_BOTTOM,
};

struct GPUTimePeriodDescriptor {
  const char* name;

  GPUTimestampIndex from;
  GPUTimestampIndex to;
};

struct CPUTimePeriodDescriptor {
  const char* name;

  CPUTimestampIndex from;
  CPUTimestampIndex to;
};

static const std::array GPU_TIME_PERIODS = std::to_array<GPUTimePeriodDescriptor>({
    {"MAIN", GPU_TIMESTAMP_INDEX_TOP, GPU_TIMESTAMP_INDEX_BOTTOM},
    {"GBuffer", GPU_TIMESTAMP_INDEX_GBUFFER_TOP, GPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM},
    {"Shadow Map", GPU_TIMESTAMP_INDEX_SHADOW_TOP, GPU_TIMESTAMP_INDEX_SHADOW_BOTTOM},
    {"Deferred", GPU_TIMESTAMP_INDEX_DEFERRED_TOP, GPU_TIMESTAMP_INDEX_DEFERRED_BOTTOM},
    {"Present", GPU_TIMESTAMP_INDEX_PRESENT_TOP, GPU_TIMESTAMP_INDEX_PRESENT_BOTTOM},
    {"ImGui", GPU_TIMESTAMP_INDEX_IMGUI_TOP, GPU_TIMESTAMP_INDEX_IMGUI_BOTTOM},
});

static const std::array CPU_TIME_PERIODS = std::to_array<CPUTimePeriodDescriptor>({
    {"Total", CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_TOP, CPU_TIMESTAMP_INDEX_PRESENT_BOTTOM},
    {"Waiting GPU", CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_TOP, CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_WAIT_FENCE},
    {"Acquire frame", CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_WAIT_FENCE, CPU_TIMESTAMP_INDEX_ACQUIRE_FRAME_BOTTOM},
    {"Draw", CPU_TIMESTAMP_INDEX_DRAW_TOP, CPU_TIMESTAMP_INDEX_DRAW_BOTTOM},
    {"Draw GBuffer", CPU_TIMESTAMP_INDEX_GBUFFER_TOP, CPU_TIMESTAMP_INDEX_GBUFFER_BOTTOM},
    {"Draw Shadow Map", CPU_TIMESTAMP_INDEX_SHADOW_TOP, CPU_TIMESTAMP_INDEX_SHADOW_BOTTOM},
    {"Draw Deferred", CPU_TIMESTAMP_INDEX_DEFERRED_TOP, CPU_TIMESTAMP_INDEX_DEFERRED_BOTTOM},
    {"Present", CPU_TIMESTAMP_INDEX_PRESENT_TOP, CPU_TIMESTAMP_INDEX_PRESENT_BOTTOM},
    {"ImGui", CPU_TIMESTAMP_INDEX_IMGUI_TOP, CPU_TIMESTAMP_INDEX_IMGUI_BOTTOM},
});

}  // namespace tr::renderer
